version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    name: "ğŸ“¦ Dependency Scanning"
    reviewers:
      - "jossmoff"
    commit-message:
      prefix: "â¬†ï¸"
    labels:
      - "dependencies"